---
name: "Bug Report"
about: "Create a bug report to help us fix the issue"
title: ""
labels: ["bug"]
assignees: []
---

## Bug Description
<!-- A clear and concise description of what the bug is -->

## Steps to Reproduce
<!-- Steps to reproduce the behavior -->

1.
2.
3.
4.

## Expected Behavior
<!-- A clear and concise description of what you expected to happen -->

## Actual Behavior
<!-- A clear and concise description of what actually happened -->

## Screenshots/Logs
<!-- If applicable, add screenshots or logs to help explain your problem -->

```
paste logs here
```

## Environment
<!-- Please complete the following information -->

- **OS**: [e.g., Arch Linux, Ubuntu 22.04]
- **Ruby version**: [e.g., 3.2.0]
- **Rails version**: [e.g., 7.1.0]
- **arerd version**: [e.g., 1.0.0]
- **Database**: [e.g., PostgreSQL 15, MySQL 8.0]

## Additional Context
<!-- Add any other context about the problem here -->
