blank_issues_enabled: false
contact_links:
  - name: "Documentation"
    url: "https://github.com/yantene/arerd/blob/main/README.md"
    about: "Please read the documentation before creating an issue"
