---
name: "Feature Request"
about: "Suggest a new feature for this project"
title: ""
labels: ["enhancement"]
assignees: []
---

## Feature Description
<!-- A clear and concise description of the feature you'd like to see -->

## Motivation
<!-- Please describe the motivation or use case for this feature -->

## Proposed Implementation
<!-- If you have ideas about how this could be implemented, please share them -->

```ruby
# Usage example (if applicable)
```

## Alternatives Considered
<!-- Describe alternatives you've considered -->

## Additional Context
<!-- Add any other context about the feature request here -->
