---
name: "Performance Issue"
about: "Report a performance-related issue"
title: ""
labels: ["performance"]
assignees: []
---

## Performance Issue
<!-- A clear and concise description of the performance issue -->

## Performance Metrics
<!-- Please provide specific performance metrics -->

- **Execution time**: [e.g., 5.2 seconds]
- **Memory usage**: [e.g., 150MB]
- **Database queries**: [e.g., 50 queries]
- **Dataset size**: [e.g., 1000 models, 500 associations]

## Expected Performance
<!-- Describe the expected or desired performance -->

## Code/Configuration
<!-- Please provide code or configuration related to the performance issue -->

```ruby
# Related code here
```

## Profiling Data
<!-- If available, please provide profiling data -->

```
Profiling results here
```

## Environment
<!-- Please complete the following information -->

- **OS**: [e.g., macOS 14.0, Ubuntu 22.04]
- **Ruby version**: [e.g., 3.2.0]
- **Rails version**: [e.g., 7.1.0]
- **arerd version**: [e.g., 1.0.0]
- **Database**: [e.g., PostgreSQL 15, MySQL 8.0]
- **Hardware**: [e.g., CPU, RAM, SSD/HDD]

## Additional Context
<!-- Add any other context about the performance issue -->
